### PR TITLE
Halim login blank credentials

### PR DESCRIPTION
**Pull request by hiltas73**
scenario outline - examples added

### CODE REVIEW

**Review by TimurGuclu — APPROVED** [review]
Good Job.

**Review by TimurGuclu — APPROVED** [review]
Good.

**Review by TimurGuclu — APPROVED** [review]
Good.

**Review by TimurGuclu — APPROVED** [review]
Good.

**Review by TimurGuclu — APPROVED** [review]
Good.

**Comment by cfr2454** [comment]
good jobb

**Review by cfr2454 — APPROVED** [review]

**Pull request merged**
