### PR TITLE
FileFunction

### PR DESCRIPTION
**Pull request by Bayraktar-github**

### CODE REVIEW

**Review by TimurGuclu — APPROVED** [review]
Good Job.

**Review by TimurGuclu — APPROVED** [review]
Good Job.

**Review by vbasman — APPROVED** [review]
Well done!

**Review by vbasman — APPROVED** [review]

**Review by TimurGuclu — APPROVED** [review]
Good Job.

**Comment by cfr2454** [comment]
well done

**Review by TimurGuclu — APPROVED** [review]

**Review by TimurGuclu — APPROVED** [review]
Good Job.

**Review by vbasman — APPROVED** [review]
Good Job!

**Pull request closed without merging**
