### PR TITLE
shahin_calendar_functionality

### PR DESCRIPTION
**Pull request by Shahinabdi1992**
calendar function created

### CODE REVIEW

**Review by TimurGuclu — APPROVED** [review]
Good Job.

**Review by TimurGuclu — APPROVED** [review]
Good Job.

**Review by vbasman — APPROVED** [review]

**Comment by cfr2454** [comment]
well done

**Review by TimurGuclu — APPROVED** [review]

**Comment by cfr2454** [comment]
its okey

**Review by TimurGuclu — APPROVED** [review]
Good Job.

**Review by vbasman — APPROVED** [review]
Good Job!

**Pull request closed without merging**
